/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vaio
 */
public class NewJFrame extends javax.swing.JFrame {
    
    String bd="matriculas";
    String user="root";
    String password="mysql";
    String host="localhost";
    String server="jdbc:mysql://"+host+"/"+bd;
    
    DefaultTableModel dtmEjemplo;       //Se usa para cargar datos a un jtable
    int[] anchos = {10, 30};       //Anchos de las columnas
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Codigo", "Pais"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //jLabel1.setText("Buscar");
        int num_filas=0;
            try{
                Connection cn;
                Statement st;
                ResultSet rs;
                
                Class.forName("com.mysql.jdbc.Driver");
                cn = DriverManager.getConnection(server,user,password);
                System.out.println("Conexión a base de datos "+server+" ... OK");
                st=cn.createStatement();
                String tsql;
        
                dtmEjemplo = new DefaultTableModel(null,new String[]{"Codigo","Pais"});
                //dtmEjemplo = (DefaultTableModel) jTable3.getModel();
                
                tsql = "select cod_pais, nom_pais from pais ";
                //tsql += "where cod_pais ='"+jTextField1.getText();
                //tsql += "'";
                
                Object datos[]=new Object[2]; //Numero de columnas de la consulta
                
                rs = st.executeQuery(tsql);
                
                while (rs.next()){ 
                     for (int i = 0; i < 2; i++) {  //Cuantas Columas regresa la consulta
                        datos[i] = rs.getObject(i + 1);
                     }
                    dtmEjemplo.addRow(datos);
                    num_filas++;
                }//fin while
                
                //dtmEjemplo.setRowCount(num_filas);
                //dtmEjemplo.setRowCount(num_filas);
                jTable3.setModel(dtmEjemplo);
                //jScrollPane3.add(jTable3);
                
                /*for(int i = 0; i < jTable3.getColumnCount(); i++) {
                    jTable3.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
                } */
                
                //jScrollPane3.setViewportView(jTable3);
                //Fijar los anchos de las columnas
                
                /*if(rs.next()){
                    jLabel1.setText(rs.getString("nom_pais"));
                }
                else{
                    jLabel1.setText("Codigo No Existe");
                }*/
                
                cn.close();
                
                }
                catch(ClassNotFoundException e){
                    e.printStackTrace();
                }
                catch(SQLException e){
                    System.out.println("estado:"+e.getSQLState());
                    System.out.println("codigo de error:"+e.getErrorCode());
                }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        //jTable table =(jTable) evt.getSource();
        //int fila;
                
        int fila = jTable3.rowAtPoint(evt.getPoint());
        
        //fila = jTable1.getModel().getRowCount();
        
        int columna = jTable3.columnAtPoint(evt.getPoint());
        String dato = null;
        //jLabel1.setText("columna");
        //String dato=String.valueOf(dtmEjemplo.getValueAt(fila.columna));
        if ((fila > -1) && (columna > -1))
            dato = String.valueOf(dtmEjemplo.getValueAt(fila, 0));
        
        //dato.trim;
        //jLabel1.setText(dato.trim());
        jLabel1.setText(String.valueOf(fila));
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
        // TODO add your handling code here:
        int fila = jTable3.getSelectedRow();
        //int columna = jTable1.columnAtPoint(evt.getPoint());
        String dato = null;
        //jLabel1.setText("columna");
        //String dato=String.valueOf(dtmEjemplo.getValueAt(fila.columna));
        if (fila > -1) 
                dato = String.valueOf(dtmEjemplo.getValueAt(fila, 0));
        
        //dato.trim;
        //jLabel1.setText(dato.trim());
        jLabel1.setText(String.valueOf(fila)); 
    }//GEN-LAST:event_jTable3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
